on:
  push:
    branches:
      - main
    paths: ['stories/**', 'src/components/**']

# Sets permissions of the NPM_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

name: Publish stories if changed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@zirro'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup npmrc
        run: node scripts/setup-npmrc.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Storybook
        run: npm run build-storybook
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify build output
        run: |
          echo "Checking storybook-static directory"
          ls -la .
          if [ -d "storybook-static" ]; then
            echo "✅ storybook-static directory found"
            ls -la storybook-static
            echo "Contents of storybook-static:"
            find storybook-static -type f | head -n 10
            echo "Total files in storybook-static: $(find storybook-static -type f | wc -l)"
          else
            echo "❌ storybook-static directory not found!"
            echo "Build command may have failed. Checking logs..."
            cat npm-error.log || echo "No npm-error.log found"
            exit 1
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static/
          name: github-pages
          retention-days: 1

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4